### ISSUE TITLE
Provide Farabi Credentials and Admin Access to Platforms

### ISSUE THREAD

**Issue by MFarabi619** [HacktheHill/tracker-app-2024#10]
```[tasklist]
### Tasks
- [x] Credentials for Development Email
- [x] Admin Access for Hack the Hill 2024 Figma
- [x] Admin Access for Vercel
- [x] Admin Access for GitHub Organization
- [x] Admin Access for OpenProject
- [x] Admin Access for Sanity CMS
- [x] Admin Access for Cloudflare
```
